"""Kaggriculture Visual Telemetry Streamlit Dashboard.

Local interactive debugging dashboard for Kaggriculture agents.
Integrates Replay 10x10 farm grids with IQL Value Net, 24-step Beam Search trees,
and Kuhn-Munkres routing cost matrices. Loads in < 1 second.
"""

from __future__ import annotations

import os
import sys
import time
from typing import Optional, Tuple

import streamlit as st

# Setup python path
WORKSPACE_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
if WORKSPACE_ROOT not in sys.path:
    sys.path.insert(0, WORKSPACE_ROOT)

from dashboard.data_loader import MatchDataset, list_available_replays, load_dataset
from dashboard.grid_view import render_farm_grid_html
from dashboard.panels import render_labor_panel, render_search_panel, render_value_panel

# -----------------------------------------------------------------------------
# Streamlit App Configuration
# -----------------------------------------------------------------------------
st.set_page_config(
    page_title="Kaggriculture Visual Telemetry Dashboard",
    page_icon="🌾",
    layout="wide",
    initial_sidebar_state="expanded",
)

# Custom Global CSS for modern dark styling
st.markdown(
    """
    <style>
    .main .block-container {
        padding-top: 1.5rem;
        padding-bottom: 2rem;
    }
    .metric-card {
        background-color: #161b22;
        border: 1px solid #30363d;
        border-radius: 8px;
        padding: 12px;
        margin-bottom: 10px;
    }
    .stTabs [data-baseweb="tab-list"] {
        gap: 12px;
    }
    .stTabs [data-baseweb="tab"] {
        padding: 8px 18px;
        border-radius: 6px;
        background-color: #161b22;
        border: 1px solid #30363d;
    }
    .stTabs [aria-selected="true"] {
        background-color: #21262d !important;
        border-color: #58a6ff !important;
        color: #58a6ff !important;
    }
    </style>
    """,
    unsafe_allow_html=True,
)


# -----------------------------------------------------------------------------
# Cached Replay Loader (<3.0s constraint)
# -----------------------------------------------------------------------------
@st.cache_data(show_spinner=False)
def get_cached_dataset(replay_path: str, telemetry_path: Optional[str]) -> MatchDataset:
    return load_dataset(replay_path, telemetry_path)


# -----------------------------------------------------------------------------
# Main Application Layout
# -----------------------------------------------------------------------------
def main() -> None:
    # 1. Sidebar Configuration & Replay Selector
    st.sidebar.title("🌾 Kaggriculture Telemetry")
    st.sidebar.caption("High-performance visual debugger for Grandmaster agent")

    available_replays = list_available_replays()
    if not available_replays:
        st.error("No replays found in `replays/`. Please provide a valid Kaggle replay.")
        st.stop()

    default_replay = available_replays[0]
    # Prefer replay 114793445 if present
    for r in available_replays:
        if "114793445" in r:
            default_replay = r
            break

    replay_idx = available_replays.index(default_replay) if default_replay in available_replays else 0
    selected_replay = st.sidebar.selectbox(
        "Select Match Replay",
        available_replays,
        index=replay_idx,
        format_func=lambda p: os.path.basename(p),
    )

    # Telemetry file selector
    default_telem = os.path.join(WORKSPACE_ROOT, "telemetry.jsonl")
    telem_input = st.sidebar.text_input(
        "Telemetry JSONL Path",
        value=default_telem if os.path.exists(default_telem) else "",
        help="Path to offline telemetry.jsonl generated by shadow_telemetry.py",
    )
    active_telem = telem_input if telem_input and os.path.exists(telem_input) else None

    # Load Dataset with benchmark
    t_start = time.perf_counter()
    with st.spinner("Indexing replay & computing IQL tensor rollouts..."):
        dataset = get_cached_dataset(selected_replay, active_telem)
    t_elapsed = time.perf_counter() - t_start

    # Sidebar KPI summary
    st.sidebar.markdown("---")
    st.sidebar.markdown(f"**Episode ID:** `{dataset.episode_id}`")
    st.sidebar.markdown(f"**Final Liquid Cash:** `${dataset.final_cash:,.1f}`")
    st.sidebar.markdown(f"**Total Steps:** `720 turns` (30 Days)")
    st.sidebar.markdown(
        f"**Engine Load Latency:** `{t_elapsed * 1000:.1f} ms` "
        f"({'⚡ <1s (Passed)' if t_elapsed < 1.0 else '✓ <3s (Passed)'})"
    )

    # Grid Display Mode
    st.sidebar.markdown("---")
    st.sidebar.markdown("### 🗺️ Farm Grid Mode")
    grid_mode = st.sidebar.radio(
        "Visual Layer",
        options=["Normal Grid", "Labor Heatmap Overlay", "Assignment Targets"],
        index=0,
        help="Switch between standard farm graphics, Kuhn-Munkres priority heatmap, and task routing targets.",
    )
    mode_key = "normal" if grid_mode == "Normal Grid" else ("heatmap" if grid_mode == "Labor Heatmap Overlay" else "assignments")

    # Quick Jump Milestones
    st.sidebar.markdown("---")
    st.sidebar.markdown("### ⚡ Quick Jump Events")
    div_t = dataset.divergence_turn

    # Manage turn state
    if "current_turn" not in st.session_state:
        st.session_state.current_turn = 0

    col_j1, col_j2 = st.sidebar.columns(2)
    with col_j1:
        if st.button("Start (T0)", use_container_width=True):
            st.session_state.current_turn = 0
            st.rerun()
        if st.button("Day 6 (NE)", use_container_width=True):
            st.session_state.current_turn = 144
            st.rerun()
        if st.button("Day 27 (Liquidation)", use_container_width=True):
            st.session_state.current_turn = 648
            st.rerun()
    with col_j2:
        if st.button("Day 3 (Plant)", use_container_width=True):
            st.session_state.current_turn = 72
            st.rerun()
        if st.button("Day 16 (Handoff)", use_container_width=True):
            st.session_state.current_turn = 384
            st.rerun()
        if st.button("Final (T719)", use_container_width=True):
            st.session_state.current_turn = 719
            st.rerun()

    if st.sidebar.button(f"🚨 Divergence (T{div_t})", type="primary", use_container_width=True):
        st.session_state.current_turn = div_t
        st.rerun()

    # 2. Main Header & Master Turn Scrubber
    st.title("🌾 Kaggriculture Decision Telemetry Dashboard")

    turn_cur = st.session_state.current_turn
    turn_obj = dataset.turns[turn_cur]

    # Scrubber controls
    ctrl1, ctrl2, ctrl3, ctrl4, ctrl5 = st.columns([1, 1, 8, 1, 1])
    with ctrl1:
        if st.button("⏮ -24h", use_container_width=True):
            st.session_state.current_turn = max(0, turn_cur - 24)
            st.rerun()
    with ctrl2:
        if st.button("◀ -1h", use_container_width=True):
            st.session_state.current_turn = max(0, turn_cur - 1)
            st.rerun()
    with ctrl3:
        new_turn = st.slider(
            "Scrub Simulation Turn (0 to 719)",
            min_value=0,
            max_value=719,
            value=turn_cur,
            step=1,
            label_visibility="collapsed",
        )
        if new_turn != turn_cur:
            st.session_state.current_turn = new_turn
            st.rerun()
    with ctrl4:
        if st.button("+1h ▶", use_container_width=True):
            st.session_state.current_turn = min(719, turn_cur + 1)
            st.rerun()
    with ctrl5:
        if st.button("+24h ⏭", use_container_width=True):
            st.session_state.current_turn = min(719, turn_cur + 24)
            st.rerun()

    # Header Badges
    st.markdown(
        f"""
        <div style="display: flex; gap: 16px; margin: 4px 0 16px 0; font-size: 14px; font-weight: 600; color: #8b949e;">
            <span>⏱️ Turn: <span style="color: #58a6ff;">{turn_obj.turn}</span> / 719</span>
            <span>📅 Day: <span style="color: #7ee787;">{turn_obj.day}</span> (Hour {turn_obj.hour:02d}:00)</span>
            <span>💰 Liquid Cash: <span style="color: #e3b341;">${turn_obj.cash:,.1f}</span></span>
            <span>🧑‍🌾 Workforce: <span style="color: #f0883e;">1 Farmer + {len(turn_obj.hands_pos)} Hands</span></span>
            <span>🗺️ Quadrants: <span style="color: #a371f7;">{', '.join(turn_obj.unlocked_quadrants)}</span></span>
        </div>
        """,
        unsafe_allow_html=True,
    )

    # 3. Main Split View: Farm Grid & Turn Inspector
    grid_col, info_col = st.columns([1.1, 0.9])

    labor_analysis = dataset.get_labor_cost_matrix(turn_cur)

    with grid_col:
        st.markdown("#### 🗺️ 10x10 Farm Terrain Grid")
        grid_html = render_farm_grid_html(
            turn_data=turn_obj,
            labor_analysis=labor_analysis,
            mode=mode_key,
        )
        st.components.v1.html(grid_html, height=640, scrolling=False)

        # Legend Bar
        st.markdown(
            """
            <div style="display: flex; flex-wrap: wrap; gap: 12px; font-size: 11px; color: #8b949e; margin-top: -10px;">
                <span>🍓 Strawberry</span>
                <span>🍈 Melon</span>
                <span>🌾 Wheat</span>
                <span>🐄 Cow</span>
                <span>🐑 Sheep</span>
                <span>🌿 Weed</span>
                <span>🏚️ Shed (Center)</span>
                <span>🧑‍🌾 Farmer (Gold)</span>
                <span>👷 Hand (Blue)</span>
            </div>
            """,
            unsafe_allow_html=True,
        )

    with info_col:
        st.markdown("#### 📊 Farm State & Tile Inspector")

        # Turn Snapshot Card
        st.markdown(
            f"""
            <div class="metric-card">
                <div style="font-weight: bold; color: #58a6ff; margin-bottom: 6px;">Match Snapshot (Turn {turn_obj.turn})</div>
                <div style="display: grid; grid-template-columns: 1fr 1fr; gap: 8px; font-size: 12px;">
                    <div>• <b>Crops Active:</b> {len(turn_obj.crops)} plots ({len(turn_obj.strawberries)} Strawberries)</div>
                    <div>• <b>Livestock:</b> {len(turn_obj.animals)} animals</div>
                    <div>• <b>Weeds Infesting:</b> {len(turn_obj.weeds)} tiles</div>
                    <div>• <b>Shed Inventory:</b> {sum(turn_obj.shed_inventory.values())} items</div>
                    <div>• <b>Wholesale Milk:</b> ${turn_obj.market_prices.get('MILK', 160.0):.0f}</div>
                    <div>• <b>Wholesale Wool:</b> ${turn_obj.market_prices.get('WOOL', 200.0):.0f}</div>
                </div>
            </div>
            """,
            unsafe_allow_html=True,
        )

        # Tile Coordinates Inspector
        st.markdown("##### 🔍 Inspect Specific Coordinates")
        ic1, ic2 = st.columns(2)
        with ic1:
            sel_x = st.selectbox("X Coordinate (0 to 9)", range(10), index=turn_obj.farmer_pos[0])
        with ic2:
            sel_y = st.selectbox("Y Coordinate (0 to 9)", range(10), index=turn_obj.farmer_pos[1])

        sel_tile = turn_obj.tiles[sel_y][sel_x] if sel_y < len(turn_obj.tiles) and sel_x < len(turn_obj.tiles[sel_y]) else None
        quadrant = "NW" if (sel_x < 5 and sel_y < 5) else ("NE" if sel_x >= 5 and sel_y < 5 else ("SW" if sel_x < 5 else "SE"))

        # Find worker at tile
        workers_at_tile = []
        if (sel_x, sel_y) == turn_obj.farmer_pos:
            workers_at_tile.append("🧑‍🌾 Farmer")
        for h_idx, h_pos in enumerate(turn_obj.hands_pos):
            if (sel_x, sel_y) == h_pos:
                workers_at_tile.append(f"👷 Hand {h_idx}")

        tile_type = "LOCKED" if sel_tile == "LOCKED" else ("EMPTY SOIL" if sel_tile is None else (
            "CENTER SHED" if (sel_x, sel_y) in {(4, 4), (5, 4), (4, 5), (5, 5)} else sel_tile.get("kind", "UNKNOWN")
        ))

        st.json({
            "coordinates": [sel_x, sel_y],
            "quadrant": quadrant,
            "tile_kind": tile_type,
            "workers_present": workers_at_tile,
            "raw_attributes": sel_tile if isinstance(sel_tile, dict) else str(sel_tile),
        })

    # 4. Three Critical Diagnostic Panels
    st.markdown("---")
    tab_value, tab_search, tab_labor = st.tabs([
        "📈 Value Panel (IQL vs Replay Reality)",
        "🌲 Search Panel (24-Step Beam Search)",
        "🚜 Labor Panel (Kuhn-Munkres Routing)",
    ])

    with tab_value:
        render_value_panel(dataset, turn_cur)

    with tab_search:
        render_search_panel(dataset, turn_cur)

    with tab_labor:
        render_labor_panel(dataset, turn_cur)


if __name__ == "__main__":
    main()
