#!/usr/bin/env python3
"""
Submission Builder for Kaggriculture.
Packages agent scripts and the kaggriculture library into Kaggle-compliant submissions
(either a multi-file submission.tar.gz or a standalone single-file main.py).
"""
import argparse
import os
import shutil
import subprocess
import sys
import tarfile
import tempfile
from pathlib import Path


ROOT_DIR = Path(__file__).resolve().parent.parent
SRC_DIR = ROOT_DIR / "src" / "kaggriculture"
SUBMISSIONS_DIR = ROOT_DIR / "submissions"
BUILD_DIR = ROOT_DIR / "build"


def build_multifile_tar(agent_path: Path, output_tar: Path) -> Path:
    """
    Bundles the agent's main.py and the kaggriculture library into a submission.tar.gz.
    Kaggle extracts this archive with main.py at root.
    """
    print(f"\n📦 Building multi-file tar.gz submission from {agent_path}...")
    BUILD_DIR.mkdir(parents=True, exist_ok=True)
    
    with tempfile.TemporaryDirectory() as tmp_dir:
        tmp_path = Path(tmp_dir)
        
        # 1. Copy main.py to root of staging dir
        shutil.copy2(agent_path, tmp_path / "main.py")
        
        # 2. Copy kaggriculture package into staging dir
        shutil.copytree(SRC_DIR, tmp_path / "kaggriculture", dirs_exist_ok=True)
        
        # 3. Create tar.gz archive
        with tarfile.open(output_tar, "w:gz") as tar:
            for item in tmp_path.iterdir():
                tar.add(item, arcname=item.name)
                
    print(f"✅ Multi-file archive created: {output_tar} ({output_tar.stat().st_size / 1024:.1f} KB)")
    return output_tar


def build_standalone_single_file(agent_path: Path, output_file: Path) -> Path:
    """
    Inlines essential library components into a single standalone self-contained main.py.
    """
    print(f"\n📄 Building single-file standalone submission from {agent_path}...")
    BUILD_DIR.mkdir(parents=True, exist_ok=True)
    
    # Read library modules in dependency order
    items_src = (SRC_DIR / "env" / "items.py").read_text()
    models_src = (SRC_DIR / "env" / "models.py").read_text()
    actions_src = (SRC_DIR / "actions" / "actions.py").read_text()
    controller_src = (SRC_DIR / "actions" / "controller.py").read_text()
    agent_src = agent_path.read_text()

    # Clean local package imports
    def clean_imports(code: str) -> str:
        lines = []
        for line in code.splitlines():
            if (
                line.startswith("from kaggriculture")
                or line.startswith("import kaggriculture")
                or "sys.path.insert" in line
            ):
                continue
            lines.append(line)
        return "\n".join(lines)

    combined_code = f"""# ==============================================================================
# Self-Contained Standalone Kaggriculture Agent
# Generated by build_submission.py
# ==============================================================================
import math
import os
import random
import sys
from dataclasses import dataclass, field
from enum import StrEnum
from typing import Any, Callable, Dict, List, Optional, Set, Tuple, Union

# --- items.py ---
{clean_imports(items_src)}

# --- models.py ---
{clean_imports(models_src)}

# --- actions.py ---
{clean_imports(actions_src)}

# --- controller.py ---
{clean_imports(controller_src)}

# --- agent logic ---
{clean_imports(agent_src)}
"""
    output_file.write_text(combined_code)
    print(f"✅ Standalone file created: {output_file} ({output_file.stat().st_size / 1024:.1f} KB)")
    return output_file


def validate_submission(target_file: Path, episode_steps: int = 48) -> bool:
    """
    Validates that the built submission executes cleanly in kaggle_environments without errors.
    """
    print(f"\n🔍 Validating submission against Kaggle Environments ({episode_steps} steps)...")
    try:
        from kaggle_environments import make
        
        env = make("kaggriculture", configuration={"episodeSteps": episode_steps})
        
        # Run test match against random agent
        steps = env.run([str(target_file), "random"])
        
        if steps and len(steps) > 0:
            final_p1_money = steps[-1][0].observation.farms[0]["money"]
            final_p2_money = steps[-1][1].observation.farms[1]["money"]
            print(f"🎉 Validation SUCCESS! Completed {len(steps)} turns.")
            print(f"   Agent Balance:    ${final_p1_money:,.2f}")
            print(f"   Opponent Balance: ${final_p2_money:,.2f}")
            return True
        else:
            print("❌ Validation FAILED: No steps returned.")
            return False
            
    except Exception as e:
        print(f"❌ Validation FAILED with error: {e}")
        import traceback
        traceback.print_exc()
        return False


def main():
    parser = argparse.ArgumentParser(description="Kaggriculture Submission Builder")
    parser.add_argument(
        "--agent", "-a",
        default="shop_opportunist",
        help="Agent template name (wheat_loop, melon_rusher, shop_opportunist) or path to main.py",
    )
    parser.add_argument(
        "--format", "-f",
        choices=["tar", "single"],
        default="tar",
        help="Submission packaging format: 'tar' for submission.tar.gz (recommended) or 'single' for standalone main.py",
    )
    parser.add_argument(
        "--no-validate",
        action="store_true",
        help="Skip dry-run validation",
    )
    parser.add_argument(
        "--message", "-m",
        default=None,
        help="Submission message for Kaggle CLI",
    )
    parser.add_argument(
        "--submit", "-s",
        action="store_true",
        help="Directly submit to Kaggle via Kaggle CLI after building and validating",
    )
    
    args = parser.parse_args()
    
    # 1. Resolve agent path
    if Path(args.agent).is_file():
        agent_path = Path(args.agent).resolve()
        agent_name = agent_path.parent.name
    elif (SUBMISSIONS_DIR / args.agent / "main.py").is_file():
        agent_path = SUBMISSIONS_DIR / args.agent / "main.py"
        agent_name = args.agent
    else:
        print(f"❌ Could not find agent at: {args.agent}")
        print(f"Available templates: {[d.name for d in SUBMISSIONS_DIR.iterdir() if d.is_dir()]}")
        sys.exit(1)
        
    print(f"🚀 Selected agent: '{agent_name}' ({agent_path})")
    
    # 2. Build submission artifact
    if args.format == "tar":
        out_path = BUILD_DIR / "submission.tar.gz"
        built_artifact = build_multifile_tar(agent_path, out_path)
    else:
        out_path = BUILD_DIR / "main.py"
        built_artifact = build_standalone_single_file(agent_path, out_path)
        
    # 3. Validate
    if not args.no_validate:
        is_valid = validate_submission(built_artifact)
        if not is_valid:
            print("\n❌ Build aborted due to validation failure. Fix errors above.")
            sys.exit(1)
            
    # 4. Display submission instructions
    msg = args.message or f"Kaggriculture {agent_name} ({args.format})"
    
    print("\n" + "=" * 70)
    print("🎯 SUBMISSION READY FOR KAGGLE")
    print("=" * 70)
    print(f"File to submit: {built_artifact}")
    print("\nRun this command to submit to Kaggle:")
    
    if args.format == "tar":
        cmd = f'uv run kaggle competitions submit kaggriculture -f "{built_artifact}" -m "{msg}"'
    else:
        cmd = f'uv run kaggle competitions submit kaggriculture -f "{built_artifact}" -m "{msg}"'
        
    print(f"  \033[1;32m{cmd}\033[0m\n")
    
    # 5. Direct submission if requested
    if args.submit:
        print("Executing Kaggle CLI submission...")
        res = subprocess.run(cmd, shell=True)
        if res.returncode == 0:
            print("🎉 Submission submitted successfully!")
        else:
            print(f"⚠️ Submission command exited with code {res.returncode}")


if __name__ == "__main__":
    main()
